// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:6b078ca1-9f5c-4d7e-bb28-53ce36cb5013",
    "aws_cognito_region": "us-east-1",
    "aws_mobile_analytics_app_id": "b6b14a8c7781447faba6d8b45755d08d",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "ToDoItems",
            "region": "us-east-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "ToDoItemsCRUD",
            "endpoint": "https://3yg8nx5562.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
